---
site_name: "NMDC BERmap"
site_description: "Browse DOE BER research programs (BRCs, SFAs, User Facilities), their studies, datasets, and variables."
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link

# for adding extra css/js see https://www.mkdocs.org/user-guide/customizing-your-theme/

plugins:
  - search
  - mknotebooks:
      execute: false
  - mermaid2:
      version: 11.4.1
  # TODO rebuild docs on schema change (https://github.com/dalito/linkml-project-copier/issues/39)
  # - gen-files:
  #     scripts:
  #       - gen_pages.py  # or any other name or path

watch:
  - src/nmdc_sfas_brcs/schema

nav:
  - Home: index.md
  - Program Browser: browser.html
  - Variable Browser: variables.html
  - Associations: associations.html
  - About: about.md
  - Schema reference: elements/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

exclude_docs: |
  /templates-linkml/

site_url: https://cmungall.github.io/nmdc-bermap
repo_url: https://github.com/cmungall/nmdc-bermap

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
