mappings:
- subject_id: profiles:engineered_microbial_strain
  subject_label: engineered microbial strain
  predicate_id: skos:exactMatch
  object_id: MIXS:0000008
  object_label: experimental factor
  mapping_justification: semapv:ManualMappingCuration
- subject_id: profiles:biocontainment_design
  subject_label: biocontainment design
  predicate_id: skos:exactMatch
  object_id: MIXS:0000008
  object_label: experimental factor
  mapping_justification: semapv:ManualMappingCuration
- subject_id: profiles:rhizosphere_deployment_context
  subject_label: rhizosphere deployment context
  predicate_id: skos:exactMatch
  object_id: MIXS:0000013
  object_label: local environmental context
  mapping_justification: semapv:ManualMappingCuration
- subject_id: profiles:rhizosphere_deployment_context
  subject_label: rhizosphere deployment context
  predicate_id: skos:exactMatch
  object_id: MIXS:0000014
  object_label: environmental medium
  mapping_justification: semapv:ManualMappingCuration
- subject_id: profiles:rhizosphere_deployment_context
  subject_label: rhizosphere deployment context
  predicate_id: skos:exactMatch
  object_id: MIXS:0000008
  object_label: experimental factor
  mapping_justification: semapv:ManualMappingCuration
- subject_id: profiles:rhizosphere_deployment_context
  subject_label: rhizosphere deployment context
  predicate_id: skos:relatedMatch
  object_id: ENVO:00005801
  object_label: rhizosphere
  mapping_justification: semapv:ManualMappingCuration
