#!/usr/bin/env python3
"""Generate an interactive HTML browser for the SFAs and BRCs database.

Uses Jinja2 templates for maintainability. Templates are in scripts/templates/.
"""

import yaml
import re
import copy
from pathlib import Path
from jinja2 import Environment, FileSystemLoader

SCRIPT_DIR = Path(__file__).parent
DB_PATH = SCRIPT_DIR.parent / "db" / "sfas-brcs.yaml"
TEMPLATE_DIR = SCRIPT_DIR / "templates"
OUTPUT_PATH = SCRIPT_DIR.parent / "docs" / "browser.html"
VARIABLE_BROWSER_OUTPUT_PATH = SCRIPT_DIR.parent / "docs" / "variables.html"
VARIABLE_INDEX_OUTPUT_PATH = SCRIPT_DIR.parent / "docs" / "variable-index.yaml"
# Intermediate indexing product: study variables derived from the LinkML profiles + SSSOM
# (schemas/), generated by `just gen-variable-index`. When present, it is the source of study
# variables for the browser, decoupling it from the inline db.variables catalog.
VARIABLE_INDEX_INPUT = SCRIPT_DIR.parent / "schemas" / "variable-index.yaml"
PROGRAM_COLLECTION_KEYS = (
    "bioenergy_research_centers",
    "genomic_science_sfas",
    "environmental_system_science_sfas",
    "user_facilities",
    "ai_projects",
    "other_programs",
)


class NoAliasDumper(yaml.SafeDumper):
    """YAML dumper that avoids anchors in generated derived indexes."""

    def ignore_aliases(self, data):
        return True


def load_db() -> dict:
    """Load the YAML database."""
    with open(DB_PATH) as f:
        return yaml.safe_load(f)


def create_jinja_env() -> Environment:
    """Create and configure Jinja2 environment."""
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        autoescape=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )
    return env


def make_anchor_id(value: str) -> str:
    """Normalize an identifier for use as an HTML anchor."""
    return re.sub(r"[^a-z0-9_-]+", "-", value.lower()).strip("-")


def resolve_sites(site_ids: list[str] | None, site_index: dict) -> list[dict]:
    """Resolve site IDs to canonical site entries."""
    if not site_ids:
        return []
    return [site_index[site_id] for site_id in site_ids if site_id in site_index]


def iter_programs(db: dict):
    """Yield all top-level research programs known to the browser."""
    for collection_key in PROGRAM_COLLECTION_KEYS:
        for program in db.get(collection_key, []) or []:
            yield collection_key, program


def _name_slug(name: str) -> str:
    return re.sub(r"_+", "_", re.sub(r"[^0-9a-z]+", "_", (name or "").lower())).strip("_")


def study_index_key(study: dict) -> str:
    """Match a db study to its key in the variable index (NMDC id local part, else name slug)."""
    sid = study.get("nmdc_study_id")
    return sid.split(":")[-1] if sid else _name_slug(study.get("name"))


def union_with_index(db: dict) -> dict:
    """All HTML is rendered from the union of db/sfas-brcs.yaml (programs/studies/datasets/sites)
    and schemas/variable-index.yaml — the single LinkML-derived product (built by
    schemas/generate_variables.py). This attaches each owner's variables (for the program pages)
    and the flat `variable_index` view (for the variable pages); the browser derives no variable
    structures of its own."""
    empty_view = {"summary": {}, "records": [], "records_by_id": {},
                  "by_bervo": [], "by_mixs": [], "without_bervo": []}
    if not VARIABLE_INDEX_INPUT.exists():
        db["variable_index"] = empty_view
        return db
    index = yaml.safe_load(VARIABLE_INDEX_INPUT.read_text()) or {}
    studies_idx = index.get("studies") or {}
    datasets_idx = index.get("datasets") or {}
    for _key, program in iter_programs(db):
        for study in program.get("studies", []) or []:
            entry = studies_idx.get(study_index_key(study))
            if entry is not None:
                study["variables"] = entry["variables"]
        for dataset in program.get("datasets", []) or []:
            entry = datasets_idx.get(_name_slug(dataset.get("name")))
            if entry is not None:
                dataset["variables"] = entry["variables"]
    db["variable_index"] = index.get("variable_index") or empty_view
    return db


def enrich_db(db: dict) -> dict:
    """Build browser-only derived structures."""
    site_index = {}
    for site in db.get("sites", []) or []:
        site["anchor_id"] = make_anchor_id(site.get("id") or site["name"])
        site["program_refs"] = []
        site_index[site["id"]] = site

    for collection_key, program in iter_programs(db):
        program["resolved_field_sites"] = resolve_sites(program.get("field_site_ids"), site_index)
        for site in program["resolved_field_sites"]:
            site["program_refs"].append(
                {
                    "id": program.get("id"),
                    "name": program.get("name"),
                }
            )

        program_id = program.get("id") or make_anchor_id(program.get("name", "program"))
        for study in program.get("studies", []) or []:
            study["anchor_id"] = make_anchor_id(f"{program_id}-study-{study.get('name', 'study')}")
            study["resolved_field_sites"] = resolve_sites(
                study.get("field_site_ids"), site_index
            )
        for dataset in program.get("datasets", []) or []:
            dataset["anchor_id"] = make_anchor_id(f"{program_id}-dataset-{dataset.get('name', 'dataset')}")

    db["sites"] = sorted(db.get("sites", []), key=lambda site: site.get("name", ""))
    return db


def generate_html(db: dict) -> str:
    """Generate the HTML page from templates."""
    env = create_jinja_env()
    template = env.get_template("browser.html.j2")
    return template.render(
        page_title="DOE BER Research Programs",
        page_subtitle="Bioenergy Research Centers, Scientific Focus Areas, AI Projects, and User Facilities",
        **db,
    )


def generate_variable_html(db: dict) -> str:
    """Generate the variable-centric HTML page from templates."""
    env = create_jinja_env()
    template = env.get_template("variable_browser.html.j2")
    return template.render(
        page_title="DOE BER Variable Browser",
        page_subtitle="Variables grouped by BERVO mappings, with unmapped variables called out for curation",
        search_placeholder="Search variables, studies, programs, or mappings...",
        **db,
    )


def write_variable_index(variable_index: dict) -> None:
    """Write the derived variable index as YAML."""
    VARIABLE_INDEX_OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    serializable_index = {
        key: copy.deepcopy(value)
        for key, value in variable_index.items()
        if key != "records_by_id"
    }
    with open(VARIABLE_INDEX_OUTPUT_PATH, "w") as f:
        yaml.dump(
            serializable_index,
            f,
            Dumper=NoAliasDumper,
            sort_keys=False,
            allow_unicode=True,
        )


def main():
    """Main entry point."""
    print(f"Loading database from {DB_PATH}")
    db = load_db()
    db = union_with_index(db)
    db = enrich_db(db)

    print("Generating HTML from templates...")
    html = generate_html(db)
    variable_html = generate_variable_html(db)
    write_variable_index(db["variable_index"])

    # Ensure output directory exists
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)

    print(f"Writing to {OUTPUT_PATH}")
    with open(OUTPUT_PATH, "w") as f:
        f.write(html)

    print(f"Writing to {VARIABLE_BROWSER_OUTPUT_PATH}")
    with open(VARIABLE_BROWSER_OUTPUT_PATH, "w") as f:
        f.write(variable_html)

    print(f"Writing to {VARIABLE_INDEX_OUTPUT_PATH}")
    print(f"Done! Open {OUTPUT_PATH} or {VARIABLE_BROWSER_OUTPUT_PATH} in a browser.")


if __name__ == "__main__":
    main()
